name: Unit Tests

on:
  pull_request:
    branches:
      - main
      - "**/main"
      - develop
      - "**/develop"

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools pytest
          pip install -r requirements.txt
          if [ -f requirements/sample-requirements.txt ]; then pip install -r requirements/sample-requirements.txt; fi
      - name: Lint with flake8
        run: |
          python -m pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --select=E9,F63,F7,F82 --show-source --max-complexity=10 --statistics
      - name: Test with pytest
        run: |
          python -m pytest tests --doctest-modules ozyamamushi

      - name: Test with pytest-cov
        id: pytest-cov-result
        run: |
          python -m pip install pytest-cov
          # pytest --cov=./tests/
          pytest --cov --cov-branch --cov-report=term-missing --junitxml=pytest.xml tests | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: arayabrain/rd-pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
